name: notesgram
description: Find studygram you need on notesgram!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_settings: ^4.1.4
  badges: ^2.0.3
  cached_network_image: ^3.1.0
  carousel_slider: ^4.1.1
  dio: ^4.0.0
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  file_picker: ^4.6.1
  floating_draggable_widget: ^2.1.1
  flutter:
    sdk: flutter
  flutter_parsed_text: ^2.2.1
  flutter_svg: ^1.0.3
  freezed: ^0.14.2
  get: ^4.1.4
  get_storage: ^2.0.2
  google_fonts: 2.2.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.4.2
  modal_bottom_sheet: ^2.1.2
  pull_to_refresh_flutter3: ^2.0.1
  photo_view: ^0.14.0
  retrofit: ^3.0.1+1
  retrofit_generator: any
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  sizer: ^2.0.15
  shimmer: ^2.0.0
  remixicon: ^1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_gen_runner:
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/theme/resources/images/launcher_icon.png"
  adaptive_icon_foreground: "lib/theme/resources/images/launcher_icon.png"
  adaptive_icon_background: "#FFFFFF"
  
flutter_gen:
  output: lib/theme/resources/gen/
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/theme/resources/images/
    - lib/theme/resources/animations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
